language: ruby
sudo: false
rvm:
  - 2.3.1
node_js:
  - v6.10.3
git:
  depth: 10
before_install:
  - nvm install v6.10.3
  - nvm use
  - npm install
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
  - export PATH=$PATH:$(dirname `nvm which node`)
script: bundle exec buildr clean noft:all --trace ; git status ; git diff
